FROM node:13-alpine

ARG PORT
ARG MONGODB_PREFIX
ARG MONDODB_USERNAME
ARG MONGODB_PASSWORD
ARG MONGODB_IPWITHPORT
ARG MONGODB_AUTHSOURCE

ENV PORT=${PORT}
ENV MONGODB_PREFIX=${MONGODB_PREFIX}
ENV MONDODB_USERNAME=${MONGODB_USERNAME}
ENV MONGODB_PASSWORD=${MONGODB_PASSWORD}
ENV MONGODB_IPWITHPORT=${MONGODB_IPWITHPORT}
ENV MONGODB_AUTHSOURCE=${MONGODB_AUTHSOURCE}

RUN mkdir -p /home/app

COPY . /home/app

RUN cd /home/app && apk update && npm install

CMD ["node","/home/app/index.js"]